config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts do
    post :like
    post :unlike
    resources :comments
  end
  resources :upload, only: [:create]
  
  root to: "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: "User"
  
  validates :post, presence: true
  validates :author, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  include AASM

  acts_as_votable
  acts_as_taggable
  
  belongs_to :owner, class_name: "User"

  has_many :comments
  
  validates_format_of :content_type, with: /video\/./
#  validates :md5, uniqueness: true
  validates :path, presence: true

  before_save :update_tag_list
  
  aasm column: 'state' do

    state :enqueued, initial: true
    state :building
    state :build_failed
    state :built

    event :start_building do
      transitions from: :enqueued, to: :building
    end

    event :mark_as_build_failed do
      transitions from: :building, to: :build_failed
    end

    event :retry_build  do
      transitions from: :build_failed, to: :enqueued
    end

    event :mark_as_built do
      transitions from: :building, to: :built
    end

  end

  protected

  def update_tag_list
    self.tag_list = String(description).scan(/#([[:alnum:]]+)/).flatten
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  mount_uploader :avatar, AvatarUploader
  
  devise :database_authenticatable, :registerable, :rememberable

  validates :username, presence: true
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    if self.action_name != "destroy"
      redirect_to request.referrer || root_path
    else
      redirect_to root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :biography, :password, :password_confirmation])
  end

  def page
    params[:page] || 1
  end

  def redirect_back_with_anchor(anchor)
    redirect_to request.referer.present? ? request.referer + "##{anchor}" : root_path
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post, only: [:create]
  
  def create
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.author = current_user
    @comment.post = @post

    authorize @comment

    if @comment.save
      redirect_to post_path(@post, anchor: "comment-#{@comment.id}")
    else
      render "posts/show"
    end
  end

  protected

  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, except: [:index, :new]
  before_action :set_comment, only: [:show]
  before_action :load_tags, only: [:index, :show]
  before_action :load_owner, only: [:index]
  
  def index
    @posts = policy_scope(Post).page(page).includes(:owner)
    @posts = @posts.where(owner_id: params[:owner_id]) if params[:owner_id]
    @posts = @posts.tagged_with(params[:tag], any: true) if params[:tag]
    
    @posts =
      case params[:sort]
      when 'likes'
        @posts.order(cached_votes_up: :desc)
      else
        @posts
      end.order(created_at: :desc)
    
    @refresh_interval = 60
  end

  def new
    @post = Post.new(owner: current_user)

    authorize @post
  end

  def edit
    authorize @post
  end

  def update
    @post.update_attributes(params.require(:post).permit(:title, :description))

    authorize @post
    
    if @post.save
      flash[:notice] = "Your video was successfuly updated"
      redirect_to @post
    else
      render 'post/edit'
    end
  end
  
  def show
    @comments = @post.comments.joins(:author).order(created_at: :asc)
    
    authorize @post
  end

  def destroy
    authorize @post

    if @post.destroy
      flash[:notice] = "Your video was successfuly deleted"
      redirect_to root_path
    else
      flash[:error] = "An unexpected error occured"
      redirect_back fallback_location: root_path
    end
  end
  
  def like
    authorize @post

    @post.liked_by current_user
    redirect_back_with_anchor "post-#{@post.id}"
  end

  def unlike
    authorize @post
    
    @post.unliked_by current_user
    redirect_back_with_anchor "post-#{@post.id}"
  end

  protected

  def load_post
    @post = Post.find(params[:id] || params[:post_id])
  end

  def set_comment
    @comment = Comment.new(author: current_user, post: @post)
  end

  def load_tags
    @tags = ActsAsTaggableOn::Tag.order(taggings_count: :desc).limit(20).pluck(:name)
  end

  def load_owner
    @owner = User.find(params[:owner_id]) if params[:owner_id]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    @post = Post.new({
                  name: params.permit("file.name")["file.name"],
                  content_type: params.permit("file.content_type")["file.content_type"],
                  path: params.permit("file.path")["file.path"],
                  md5: params.permit("file.md5")["file.md5"],
                  size: params.permit("file.size")["file.size"].to_i,
                  title: params.permit("title")["title"],
                  description: params.permit("description")["description"],
                  owner: current_user
    })

    if @post.save
      redirect_to posts_path
    else
      render 'posts/new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= t(:"errors.template.header", model: t(:"activerecord.models.#{objects.compact.first.class.name.downcase}"), count: objects.compact.first.errors.messages.size)
    options[:message] ||= t(:"errors.template.body")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, id: "error_explanation", class: "notification is-danger is-radiusless") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  def video_path(post)
    ENV["PUBLIC_VIDEOS_PATH"] + "/" + post.name
  end

  def thumbnail_path(post)
    ENV["PUBLIC_VIDEOS_PATH"] + "/" + post.thumbnail
  end

  def format_text(text)
    formatted_text = simple_format(hashtags_links(h(text)))
    linked_text = auto_link(formatted_text, :html => { :target => '_blank', :rel => 'noopener', class: 'ellipsis' }).gsub("\n\n", '<br />').gsub("<p></p>", '').html_safe
  end

  def hashtags_links(text)
    text.gsub(/#([[:alnum:]]+)/, link_to("/posts?tag=\\1") { "#\\1" }.html_safe)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nanotube</title>
    <%= csrf_meta_tags %>

    <meta content='width=device-width, initial-scale=1' name='viewport'>
    <% if @refresh_interval.present? %>
    <meta http-equiv="refresh" content="<%= @refresh_interval %>">
    <% end %>

    <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path('apple-icon-57x57.png') %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= image_path('apple-icon-60x60.png') %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path('apple-icon-72x72.png') %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path('apple-icon-76x76.png') %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path('apple-icon-114x114.png') %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path('apple-icon-120x120.png') %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path('apple-icon-144x144.png') %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path('apple-icon-152x152.png') %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path('apple-icon-180x180.png') %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= image_path('android-icon-192x192.png') %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= image_path('favicon-32x32.png') %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= image_path('favicon-96x96.png') %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= image_path('favicon-16x16.png') %>">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= image_path('ms-icon-144x144.png') %>">
    <meta name="theme-color" content="#ffffff">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <% if user_signed_in? || Rails.configuration.are_videos_public %>
    <nav class="navbar">
      <%= active_link_to root_path, class: "navbar-item", class_active: "is-active", active: :exact do %>
	Last videos
      <% end %>

      <%= active_link_to posts_path(sort: :likes), class: "navbar-item", class_active: "is-active", active: :exact do %>
	Best rated
      <% end %>

      <% if user_signed_in? %>
      <%= active_link_to posts_path(owner_id: current_user.id), class: "navbar-item", class_active: "is-active", active: :exact do %>
	My videos
      <% end %>
      <% end %>
      <div class="navbar-item search-item">
	<form action="/posts">
	  <p class="control has-icons-left">
	    <span class="icon is-small is-left">
	      <i class="fa fa-search"></i>
	    </span>
	    <input class="input" type="text" placeholder="Find a video" name="tag" value="<%= params[:tag] %>">
	    <button class="button">
	      Search
	    </button>
	  </p>
	</form>
      </div>

      <% if user_signed_in? %>
      <div class="navbar-end">
	<%= active_link_to(edit_user_registration_path, class: "navbar-item", class_active: "is-active") do %>
	<%= current_user.username %>
	<%= image_tag current_user.avatar_url, alt: current_user.username, class: "navbar-avatar" %>
	<% end %>
	<div class="navbar-item">
	  <p class="control">
	    <%= active_link_to new_post_path, class: "button is-primary", class_active: "is-active" do %>
	    <span class="icon is-small">
	      <i class="fa fa-upload"></i>
	    </span>
	    <span>Upload</span>
	    <% end %>
	  </p>
	</div>
      </div>
      <% else %>
      <%= active_link_to new_user_session_path, class: "navbar-item", class_active: "is-active", active: :exact do %>
      Sign in
      <% end %>
      	<div class="navbar-item">
	  <p class="control">
	    <%= active_link_to new_user_registration_path, class: "button is-primary", class_active: "is-active" do %>
	    <span>Sign up</span>
	    <% end %>
	  </p>
	</div>
      <% end %>
    </nav>
    <% end %>

    <% if notice %>
    <div class="notification is-success">
      <%= notice %>
    </div>
    <% end %>
    <% if alert %>
    <div class="notification is-danger">
      <%= alert %>
    </div>
    <% end %>

    <section class="section">

      <% if @tags.present? %>
      <div class="columns">
	<div class="column is-2">
	  <aside class="menu">
	    <p class="menu-label">
	      Popular tags
	    </p>
	    <ul class="menu-list">
	      <% @tags.each do |tag| %>
	      <li>
		<%= link_to tag, posts_path(tag: tag), class: "link" %>
	      </li>
	      <% end %>
	    </ul>
	  </aside>
	</div>
	<div class="column is-10">
	  <main class="container is-fullhd">
	    <%= yield %>
	  </main>
	</div>
      </div>
      <% else %>
      <main class="container is-fullhd">
	<%= yield %>
      </main>
      <% end %>
    </section>
  </body>
</html>

app/views/posts/_card_content.html.erb
<div class="card-content">
  <div class="media">
    <div class="media-left">
      <figure class="image is-48x48">
	<%= link_to posts_path(owner_id: post.owner.id) do %>
	<%= image_tag post.owner.avatar_url, alt: post.owner.username %>
	<% end %>
      </figure>
    </div>
    <div class="media-content">
      <p class="title is-4 ellipsis">
	<%= link_to post.owner.username, posts_path(owner_id: post.owner.id) %><br />
	<small class="date"><%= post.created_at.strftime("%m/%d/%Y") %></small>
      </p>
    </div>

    <div class="media-right">
      <% if user_signed_in? %>
      
      <% if current_user.liked?(post) %>
      <%= button_to post_unlike_path(post), class: "level-item button is-white is-paddingless is-marginless" do %>
      <span class="icon"><i class="fa fa-heart"></i></span>
      <% end %>
      <% else %>
      <%= button_to post_like_path(post), class: "level-item button is-white is-paddingless is-marginless" do %>
      <span class="icon"><i class="fa fa-heart-o"></i></span>
      <% end %>
      <% end %>
      <% else %>

      <div class="level-item button is-white is-paddingless is-marginless">
	<span class="icon"><i class="fa fa-heart-o"></i></span>
      </div>

      <% end %>
      <small class="likes-count"><%= post.cached_votes_up %></small>
    </div>
  </div>

  <div class="content">
    <p class="ellipsis">
      <% if post.title.present? %>
      <strong><%= post.title %></strong>
      <% else %>
      <em>No title</em>
      <% end %>
    </p>
    
    <% if full && post.description.present? %>
    <%= format_text post.description %>
    <% end %>

    <% if full && policy(post).update? %>
    <nav class="level">
      <div class="level-left">
	<div class="level-item">
	  <%= link_to edit_post_path(post) do %>
	  Edit
	  <% end %>
	</div>
      </div>
    </nav>
    <% end %>
      
  </div>

</div>

app/views/posts/edit.html.erb
<div class="columns">
  <div class="column is-6 is-offset-3">
    <%= form_for @post do |f| %>
      <div class="card">
	<%= error_messages_for(@post) %>
	<div class="card-content">
	  <div class="content">

	    <div class="field">
	      <%= f.label :title, class: "label" %>
	      <div class="control">
		<%= f.text_field :title, autofocus: true, class: "input" %>
	      </div>
	    </div>

	    <div class="field">
	      <%= f.label :description, class: "label" %>
	      <div class="control">
		<%= f.text_area :description, rows: 4, class: "textarea" %>
	      </div>
	      <p class="help">Include <a>#hashtags</a> to make your video easier to find.</p>
	    </div>

	  </div>
	</div>
	<footer class="card-footer">
	  <p class="card-footer-item">
	    <button type="submit" name="submit" class="button is-primary">
	      <span>Save</span>
	    </button>
	  </p>
	</footer>
      </div>
      <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<% if @owner.present? %>
<section class="section">
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64">
	<%= image_tag @owner.avatar_url, alt: @owner.username %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
	<p>
	  <strong><%= @owner.username %></strong>
	  <br>
	  <%= @owner.biography %>
	</p>
      </div>
    </div>
  </article>
</section>
<% end %>

<div class="columns is-multiline">
  <% @posts.each do |post| %>
  <div class="column is-one-third" id="post-<%= post.id %>">
    <div class="card">
      <% if post.built? && post.thumbnail.present? %>
      <div class="card-image">
	<figure class="image is-4by3">
	  <%= link_to post do %>
	  <img src="<%= thumbnail_path(post) %>" alt="<%= post.title %>">
	  <% end %>
	</figure>
      </div>
      <% elsif post.enqueued? || post.building? %>
      <div class="card-image">
	<figure class="image is-4by3">
	  <%= link_to post do %>
	  <div class="image-container">
	    <div class="circular-container">
	      <div class="circle circular-loader1">
		<div class="circle circular-loader2">
		</div>
	      </div>
	    </div>
	  </div>
	  <% end %>
	</figure>
      </div>
      <% elsif post.build_failed? %>
      <div class="card-image">
	<figure class="image is-4by3">
	  <%= link_to post do %>
	  <div class="image-container">
	    <span class="icon is-large">
	      <i class="fa fa-exclamation-circle"></i>
	    </span>
	  </div>
	  <% end %>
	</figure>
      </div>
      <% end %>
      <%= render partial: "posts/card_content", locals: { post: post, full: false } %>
    </div>
  </div>
  <% end %>
</div>

<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="columns">
  <div class="column is-6 is-offset-3">
    <form name="upload" method="POST" enctype="multipart/form-data" action="/upload">
      <div class="card">
	<%= error_messages_for(@post) %>
	<div class="card-content">
	  <div class="content">

	    <div class="field">
	      <label class="label" for="title">Title</label>
	      <div class="control">
		<input class="input" type="text" name="title" id="title" />
	      </div>
	    </div>

	    <div class="field">
	      <label class="label" for="description">Description</label>
	      <div class="control">
		<textarea class="textarea" name="description" id="description" rows="4"></textarea>
	      </div>
	      <p class="help">Include <a>#hashtags</a> to make your video easier to find.</p>
	    </div>

	    <div class="field">
	      <label class="label" for="title">Video</label>
	      <div class="control">
		<input type="file" name="file" id="file">
	      </div>
	    </div>
	    
	  </div>
	</div>
	<footer class="card-footer">
	  <p class="card-footer-item has-text-right">
	    <button type="submit" name="submit" class="button is-primary">
	      <span class="icon is-small">
		<i class="fa fa-upload"></i>
	      </span>
	      <span>Upload</span>
	    </button>
	  </p>
	</footer>
      </div>
    </form>
  </div>
</div>

app/views/posts/show.html.erb
<% if @post.built? %>
<video src="<%= video_path(@post) %>" controls="controls" autoplay="autoplay"></video>
<% elsif @post.enqueued? || @post.building? %>
<div class="notification is-primary">
Your video is currently being processed.
</div>
<% elsif @post.build_failed? %>
<div class="notification is-danger">
  There was an error with your video.
</div>
<% end %>


<%= render partial: "posts/card_content", locals: { post: @post, full: true } %>

<% @comments.order(created_at: :asc).each do |comment| %>
<article class="media" id="comment-<%= comment.id %>">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= link_to posts_path(owner_id: comment.author_id) do %>
      <%= image_tag comment.author.avatar_url, alt: comment.author.username %>
      <% end %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p class="is-marginless">
	<%= link_to posts_path(owner_id: comment.author_id) do %>
	<strong>
	  <%= comment.author.username %>
	</strong>
	<% end %>
      </p>
      <%= format_text(comment.body) %>
    </div>
  </div>
</article>
<% end %>

<% if user_signed_in? %>
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag current_user.avatar_url, alt: current_user.username %>
    </p>
  </figure>
  <div class="media-content">
    <%= form_for [@post, @comment], class: "media" do |f| %>
    <div class="field">
      <p class="control">
	<%= f.text_area :body, placeholder: "Add a comment...", class: "textarea" %>
      </p>
    </div>
    <div class="field">
      <p class="control">
	<%= f.button type: "submit", class: "button" do %>
	Post comment
	<% end %>
      </p>
    </div>
    <% end %>
  </div>
</article>
<% end %>